// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefundOperatorType int32

const (
	RefundOperatorType_ROT_Universe RefundOperatorType = 0
	RefundOperatorType_ROT_ADMIN    RefundOperatorType = 1
	RefundOperatorType_ROT_MICRO    RefundOperatorType = 2
)

var RefundOperatorType_name = map[int32]string{
	0: "ROT_Universe",
	1: "ROT_ADMIN",
	2: "ROT_MICRO",
}

var RefundOperatorType_value = map[string]int32{
	"ROT_Universe": 0,
	"ROT_ADMIN":    1,
	"ROT_MICRO":    2,
}

func (x RefundOperatorType) String() string {
	return proto.EnumName(RefundOperatorType_name, int32(x))
}

func (RefundOperatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

type OrderType int32

const (
	OrderType_OT_Universe OrderType = 0
	OrderType_OT_SITE     OrderType = 1
	OrderType_OT_GOODS    OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "OT_Universe",
	1: "OT_SITE",
	2: "OT_GOODS",
}

var OrderType_value = map[string]int32{
	"OT_Universe": 0,
	"OT_SITE":     1,
	"OT_GOODS":    2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

type CreateOrderReq struct {
	OpenId               string    `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Body                 string    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	TotalFee             int32     `protobuf:"varint,3,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	Remark               string    `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderType            OrderType `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=order.OrderType" json:"order_type,omitempty"`
	GoodsId              int32     `protobuf:"varint,6,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Contacts             string    `protobuf:"bytes,7,opt,name=contacts,proto3" json:"contacts,omitempty"`
	ContactNumber        string    `protobuf:"bytes,8,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *CreateOrderReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateOrderReq) GetTotalFee() int32 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *CreateOrderReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CreateOrderReq) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_OT_Universe
}

func (m *CreateOrderReq) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *CreateOrderReq) GetContacts() string {
	if m != nil {
		return m.Contacts
	}
	return ""
}

func (m *CreateOrderReq) GetContactNumber() string {
	if m != nil {
		return m.ContactNumber
	}
	return ""
}

type CreateOrderResp struct {
	OrderNo              string   `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	NonceStr             string   `protobuf:"bytes,4,opt,name=NonceStr,proto3" json:"NonceStr,omitempty"`
	PrepayId             string   `protobuf:"bytes,5,opt,name=PrepayId,proto3" json:"PrepayId,omitempty"`
	SignType             string   `protobuf:"bytes,6,opt,name=SignType,proto3" json:"SignType,omitempty"`
	PaySign              string   `protobuf:"bytes,7,opt,name=PaySign,proto3" json:"PaySign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResp) Reset()         { *m = CreateOrderResp{} }
func (m *CreateOrderResp) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResp) ProtoMessage()    {}
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CreateOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResp.Unmarshal(m, b)
}
func (m *CreateOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResp.Marshal(b, m, deterministic)
}
func (m *CreateOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResp.Merge(m, src)
}
func (m *CreateOrderResp) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResp.Size(m)
}
func (m *CreateOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResp proto.InternalMessageInfo

func (m *CreateOrderResp) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *CreateOrderResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CreateOrderResp) GetNonceStr() string {
	if m != nil {
		return m.NonceStr
	}
	return ""
}

func (m *CreateOrderResp) GetPrepayId() string {
	if m != nil {
		return m.PrepayId
	}
	return ""
}

func (m *CreateOrderResp) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *CreateOrderResp) GetPaySign() string {
	if m != nil {
		return m.PaySign
	}
	return ""
}

type WechatOrderNotifyReq struct {
	ReqData              []byte   `protobuf:"bytes,1,opt,name=ReqData,proto3" json:"ReqData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatOrderNotifyReq) Reset()         { *m = WechatOrderNotifyReq{} }
func (m *WechatOrderNotifyReq) String() string { return proto.CompactTextString(m) }
func (*WechatOrderNotifyReq) ProtoMessage()    {}
func (*WechatOrderNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *WechatOrderNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatOrderNotifyReq.Unmarshal(m, b)
}
func (m *WechatOrderNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatOrderNotifyReq.Marshal(b, m, deterministic)
}
func (m *WechatOrderNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatOrderNotifyReq.Merge(m, src)
}
func (m *WechatOrderNotifyReq) XXX_Size() int {
	return xxx_messageInfo_WechatOrderNotifyReq.Size(m)
}
func (m *WechatOrderNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatOrderNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_WechatOrderNotifyReq proto.InternalMessageInfo

func (m *WechatOrderNotifyReq) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

type WechatOrderNotifyResp struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatOrderNotifyResp) Reset()         { *m = WechatOrderNotifyResp{} }
func (m *WechatOrderNotifyResp) String() string { return proto.CompactTextString(m) }
func (*WechatOrderNotifyResp) ProtoMessage()    {}
func (*WechatOrderNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *WechatOrderNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatOrderNotifyResp.Unmarshal(m, b)
}
func (m *WechatOrderNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatOrderNotifyResp.Marshal(b, m, deterministic)
}
func (m *WechatOrderNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatOrderNotifyResp.Merge(m, src)
}
func (m *WechatOrderNotifyResp) XXX_Size() int {
	return xxx_messageInfo_WechatOrderNotifyResp.Size(m)
}
func (m *WechatOrderNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatOrderNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_WechatOrderNotifyResp proto.InternalMessageInfo

func (m *WechatOrderNotifyResp) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type RefundOrderReq struct {
	Uid                  uint32             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo              string             `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OperatorType         RefundOperatorType `protobuf:"varint,3,opt,name=operator_type,json=operatorType,proto3,enum=order.RefundOperatorType" json:"operator_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RefundOrderReq) Reset()         { *m = RefundOrderReq{} }
func (m *RefundOrderReq) String() string { return proto.CompactTextString(m) }
func (*RefundOrderReq) ProtoMessage()    {}
func (*RefundOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *RefundOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundOrderReq.Unmarshal(m, b)
}
func (m *RefundOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundOrderReq.Marshal(b, m, deterministic)
}
func (m *RefundOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundOrderReq.Merge(m, src)
}
func (m *RefundOrderReq) XXX_Size() int {
	return xxx_messageInfo_RefundOrderReq.Size(m)
}
func (m *RefundOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefundOrderReq proto.InternalMessageInfo

func (m *RefundOrderReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RefundOrderReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *RefundOrderReq) GetOperatorType() RefundOperatorType {
	if m != nil {
		return m.OperatorType
	}
	return RefundOperatorType_ROT_Universe
}

type RefundOrderResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundOrderResp) Reset()         { *m = RefundOrderResp{} }
func (m *RefundOrderResp) String() string { return proto.CompactTextString(m) }
func (*RefundOrderResp) ProtoMessage()    {}
func (*RefundOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *RefundOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundOrderResp.Unmarshal(m, b)
}
func (m *RefundOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundOrderResp.Marshal(b, m, deterministic)
}
func (m *RefundOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundOrderResp.Merge(m, src)
}
func (m *RefundOrderResp) XXX_Size() int {
	return xxx_messageInfo_RefundOrderResp.Size(m)
}
func (m *RefundOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefundOrderResp proto.InternalMessageInfo

type WechatRefundNotifyReq struct {
	ReqData              []byte   `protobuf:"bytes,1,opt,name=ReqData,proto3" json:"ReqData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatRefundNotifyReq) Reset()         { *m = WechatRefundNotifyReq{} }
func (m *WechatRefundNotifyReq) String() string { return proto.CompactTextString(m) }
func (*WechatRefundNotifyReq) ProtoMessage()    {}
func (*WechatRefundNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *WechatRefundNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatRefundNotifyReq.Unmarshal(m, b)
}
func (m *WechatRefundNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatRefundNotifyReq.Marshal(b, m, deterministic)
}
func (m *WechatRefundNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatRefundNotifyReq.Merge(m, src)
}
func (m *WechatRefundNotifyReq) XXX_Size() int {
	return xxx_messageInfo_WechatRefundNotifyReq.Size(m)
}
func (m *WechatRefundNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatRefundNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_WechatRefundNotifyReq proto.InternalMessageInfo

func (m *WechatRefundNotifyReq) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

type WechatRefundNotifyResp struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatRefundNotifyResp) Reset()         { *m = WechatRefundNotifyResp{} }
func (m *WechatRefundNotifyResp) String() string { return proto.CompactTextString(m) }
func (*WechatRefundNotifyResp) ProtoMessage()    {}
func (*WechatRefundNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *WechatRefundNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatRefundNotifyResp.Unmarshal(m, b)
}
func (m *WechatRefundNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatRefundNotifyResp.Marshal(b, m, deterministic)
}
func (m *WechatRefundNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatRefundNotifyResp.Merge(m, src)
}
func (m *WechatRefundNotifyResp) XXX_Size() int {
	return xxx_messageInfo_WechatRefundNotifyResp.Size(m)
}
func (m *WechatRefundNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatRefundNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_WechatRefundNotifyResp proto.InternalMessageInfo

func (m *WechatRefundNotifyResp) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type OrderInfo struct {
	OrderNo              string           `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TotalPrice           int32            `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	PayTime              string           `protobuf:"bytes,3,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	Status               int32            `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string           `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	BackRemark           string           `protobuf:"bytes,6,opt,name=back_remark,json=backRemark,proto3" json:"back_remark,omitempty"`
	BackTime             string           `protobuf:"bytes,7,opt,name=back_time,json=backTime,proto3" json:"back_time,omitempty"`
	WxTradeNo            string           `protobuf:"bytes,8,opt,name=wx_trade_no,json=wxTradeNo,proto3" json:"wx_trade_no,omitempty"`
	CreateAt             string           `protobuf:"bytes,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	ProductType          int32            `protobuf:"varint,10,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	GoodsId              int32            `protobuf:"varint,11,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	StatusName           string           `protobuf:"bytes,12,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	WechatPayParam       *CreateOrderResp `protobuf:"bytes,13,opt,name=wechat_pay_param,json=wechatPayParam,proto3" json:"wechat_pay_param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *OrderInfo) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderInfo) GetPayTime() string {
	if m != nil {
		return m.PayTime
	}
	return ""
}

func (m *OrderInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *OrderInfo) GetBackRemark() string {
	if m != nil {
		return m.BackRemark
	}
	return ""
}

func (m *OrderInfo) GetBackTime() string {
	if m != nil {
		return m.BackTime
	}
	return ""
}

func (m *OrderInfo) GetWxTradeNo() string {
	if m != nil {
		return m.WxTradeNo
	}
	return ""
}

func (m *OrderInfo) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *OrderInfo) GetProductType() int32 {
	if m != nil {
		return m.ProductType
	}
	return 0
}

func (m *OrderInfo) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *OrderInfo) GetStatusName() string {
	if m != nil {
		return m.StatusName
	}
	return ""
}

func (m *OrderInfo) GetWechatPayParam() *CreateOrderResp {
	if m != nil {
		return m.WechatPayParam
	}
	return nil
}

type GetOrderInfoReq struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderInfoReq) Reset()         { *m = GetOrderInfoReq{} }
func (m *GetOrderInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderInfoReq) ProtoMessage()    {}
func (*GetOrderInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *GetOrderInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderInfoReq.Unmarshal(m, b)
}
func (m *GetOrderInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderInfoReq.Marshal(b, m, deterministic)
}
func (m *GetOrderInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderInfoReq.Merge(m, src)
}
func (m *GetOrderInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderInfoReq.Size(m)
}
func (m *GetOrderInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderInfoReq proto.InternalMessageInfo

func (m *GetOrderInfoReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type GetOrderInfoResp struct {
	Info                 *OrderInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOrderInfoResp) Reset()         { *m = GetOrderInfoResp{} }
func (m *GetOrderInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetOrderInfoResp) ProtoMessage()    {}
func (*GetOrderInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *GetOrderInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderInfoResp.Unmarshal(m, b)
}
func (m *GetOrderInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderInfoResp.Marshal(b, m, deterministic)
}
func (m *GetOrderInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderInfoResp.Merge(m, src)
}
func (m *GetOrderInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetOrderInfoResp.Size(m)
}
func (m *GetOrderInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderInfoResp proto.InternalMessageInfo

func (m *GetOrderInfoResp) GetInfo() *OrderInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetOrdersInfoReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersInfoReq) Reset()         { *m = GetOrdersInfoReq{} }
func (m *GetOrdersInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetOrdersInfoReq) ProtoMessage()    {}
func (*GetOrdersInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *GetOrdersInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersInfoReq.Unmarshal(m, b)
}
func (m *GetOrdersInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersInfoReq.Marshal(b, m, deterministic)
}
func (m *GetOrdersInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersInfoReq.Merge(m, src)
}
func (m *GetOrdersInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetOrdersInfoReq.Size(m)
}
func (m *GetOrdersInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersInfoReq proto.InternalMessageInfo

func (m *GetOrdersInfoReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetOrdersInfoResp struct {
	List                 []*OrderInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOrdersInfoResp) Reset()         { *m = GetOrdersInfoResp{} }
func (m *GetOrdersInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetOrdersInfoResp) ProtoMessage()    {}
func (*GetOrdersInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *GetOrdersInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersInfoResp.Unmarshal(m, b)
}
func (m *GetOrdersInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersInfoResp.Marshal(b, m, deterministic)
}
func (m *GetOrdersInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersInfoResp.Merge(m, src)
}
func (m *GetOrdersInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetOrdersInfoResp.Size(m)
}
func (m *GetOrdersInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersInfoResp proto.InternalMessageInfo

func (m *GetOrdersInfoResp) GetList() []*OrderInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type HasPayingOrderReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductType          int32    `protobuf:"varint,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasPayingOrderReq) Reset()         { *m = HasPayingOrderReq{} }
func (m *HasPayingOrderReq) String() string { return proto.CompactTextString(m) }
func (*HasPayingOrderReq) ProtoMessage()    {}
func (*HasPayingOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *HasPayingOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPayingOrderReq.Unmarshal(m, b)
}
func (m *HasPayingOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPayingOrderReq.Marshal(b, m, deterministic)
}
func (m *HasPayingOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPayingOrderReq.Merge(m, src)
}
func (m *HasPayingOrderReq) XXX_Size() int {
	return xxx_messageInfo_HasPayingOrderReq.Size(m)
}
func (m *HasPayingOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPayingOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_HasPayingOrderReq proto.InternalMessageInfo

func (m *HasPayingOrderReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *HasPayingOrderReq) GetProductType() int32 {
	if m != nil {
		return m.ProductType
	}
	return 0
}

type HasPayingOrderResp struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasPayingOrderResp) Reset()         { *m = HasPayingOrderResp{} }
func (m *HasPayingOrderResp) String() string { return proto.CompactTextString(m) }
func (*HasPayingOrderResp) ProtoMessage()    {}
func (*HasPayingOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{14}
}

func (m *HasPayingOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPayingOrderResp.Unmarshal(m, b)
}
func (m *HasPayingOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPayingOrderResp.Marshal(b, m, deterministic)
}
func (m *HasPayingOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPayingOrderResp.Merge(m, src)
}
func (m *HasPayingOrderResp) XXX_Size() int {
	return xxx_messageInfo_HasPayingOrderResp.Size(m)
}
func (m *HasPayingOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPayingOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_HasPayingOrderResp proto.InternalMessageInfo

func (m *HasPayingOrderResp) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

type CancelOrderReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo              string   `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderReq) Reset()         { *m = CancelOrderReq{} }
func (m *CancelOrderReq) String() string { return proto.CompactTextString(m) }
func (*CancelOrderReq) ProtoMessage()    {}
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{15}
}

func (m *CancelOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderReq.Unmarshal(m, b)
}
func (m *CancelOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderReq.Marshal(b, m, deterministic)
}
func (m *CancelOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderReq.Merge(m, src)
}
func (m *CancelOrderReq) XXX_Size() int {
	return xxx_messageInfo_CancelOrderReq.Size(m)
}
func (m *CancelOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderReq proto.InternalMessageInfo

func (m *CancelOrderReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CancelOrderReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type CancelOrderResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResp) Reset()         { *m = CancelOrderResp{} }
func (m *CancelOrderResp) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResp) ProtoMessage()    {}
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{16}
}

func (m *CancelOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResp.Unmarshal(m, b)
}
func (m *CancelOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResp.Marshal(b, m, deterministic)
}
func (m *CancelOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResp.Merge(m, src)
}
func (m *CancelOrderResp) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResp.Size(m)
}
func (m *CancelOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResp proto.InternalMessageInfo

type AdminCancelOrderReq struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminCancelOrderReq) Reset()         { *m = AdminCancelOrderReq{} }
func (m *AdminCancelOrderReq) String() string { return proto.CompactTextString(m) }
func (*AdminCancelOrderReq) ProtoMessage()    {}
func (*AdminCancelOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{17}
}

func (m *AdminCancelOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminCancelOrderReq.Unmarshal(m, b)
}
func (m *AdminCancelOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminCancelOrderReq.Marshal(b, m, deterministic)
}
func (m *AdminCancelOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminCancelOrderReq.Merge(m, src)
}
func (m *AdminCancelOrderReq) XXX_Size() int {
	return xxx_messageInfo_AdminCancelOrderReq.Size(m)
}
func (m *AdminCancelOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminCancelOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminCancelOrderReq proto.InternalMessageInfo

func (m *AdminCancelOrderReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type AdminCancelOrderResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminCancelOrderResp) Reset()         { *m = AdminCancelOrderResp{} }
func (m *AdminCancelOrderResp) String() string { return proto.CompactTextString(m) }
func (*AdminCancelOrderResp) ProtoMessage()    {}
func (*AdminCancelOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{18}
}

func (m *AdminCancelOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminCancelOrderResp.Unmarshal(m, b)
}
func (m *AdminCancelOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminCancelOrderResp.Marshal(b, m, deterministic)
}
func (m *AdminCancelOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminCancelOrderResp.Merge(m, src)
}
func (m *AdminCancelOrderResp) XXX_Size() int {
	return xxx_messageInfo_AdminCancelOrderResp.Size(m)
}
func (m *AdminCancelOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminCancelOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminCancelOrderResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("order.RefundOperatorType", RefundOperatorType_name, RefundOperatorType_value)
	proto.RegisterEnum("order.OrderType", OrderType_name, OrderType_value)
	proto.RegisterType((*CreateOrderReq)(nil), "order.CreateOrderReq")
	proto.RegisterType((*CreateOrderResp)(nil), "order.CreateOrderResp")
	proto.RegisterType((*WechatOrderNotifyReq)(nil), "order.WechatOrderNotifyReq")
	proto.RegisterType((*WechatOrderNotifyResp)(nil), "order.WechatOrderNotifyResp")
	proto.RegisterType((*RefundOrderReq)(nil), "order.RefundOrderReq")
	proto.RegisterType((*RefundOrderResp)(nil), "order.RefundOrderResp")
	proto.RegisterType((*WechatRefundNotifyReq)(nil), "order.WechatRefundNotifyReq")
	proto.RegisterType((*WechatRefundNotifyResp)(nil), "order.WechatRefundNotifyResp")
	proto.RegisterType((*OrderInfo)(nil), "order.OrderInfo")
	proto.RegisterType((*GetOrderInfoReq)(nil), "order.GetOrderInfoReq")
	proto.RegisterType((*GetOrderInfoResp)(nil), "order.GetOrderInfoResp")
	proto.RegisterType((*GetOrdersInfoReq)(nil), "order.GetOrdersInfoReq")
	proto.RegisterType((*GetOrdersInfoResp)(nil), "order.GetOrdersInfoResp")
	proto.RegisterType((*HasPayingOrderReq)(nil), "order.HasPayingOrderReq")
	proto.RegisterType((*HasPayingOrderResp)(nil), "order.HasPayingOrderResp")
	proto.RegisterType((*CancelOrderReq)(nil), "order.CancelOrderReq")
	proto.RegisterType((*CancelOrderResp)(nil), "order.CancelOrderResp")
	proto.RegisterType((*AdminCancelOrderReq)(nil), "order.AdminCancelOrderReq")
	proto.RegisterType((*AdminCancelOrderResp)(nil), "order.AdminCancelOrderResp")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xc5, 0x69, 0xd3, 0xc4, 0xd7, 0x49, 0xea, 0x0e, 0xbb, 0x5d, 0x37, 0x5d, 0x68, 0xb0, 0x16,
	0x88, 0x56, 0x68, 0x59, 0xca, 0x03, 0x20, 0xf1, 0x55, 0xda, 0x65, 0x37, 0xaa, 0x36, 0x09, 0xd3,
	0x20, 0x1e, 0xad, 0x69, 0x3c, 0xe9, 0x5a, 0xdb, 0x78, 0xa6, 0x9e, 0x09, 0x5d, 0x3f, 0xf0, 0xc0,
	0x1f, 0xe2, 0x95, 0x5f, 0x87, 0x84, 0x66, 0x3c, 0x4e, 0x63, 0xc7, 0xa9, 0x10, 0x6f, 0xbe, 0x5f,
	0x73, 0xef, 0x9d, 0x73, 0xce, 0xc8, 0xe0, 0xb0, 0x24, 0xa4, 0xc9, 0x33, 0x9e, 0x30, 0xc9, 0x50,
	0x5d, 0x1b, 0xfe, 0x9f, 0x35, 0xe8, 0x9c, 0x26, 0x94, 0x48, 0x3a, 0x52, 0x36, 0xa6, 0x37, 0xe8,
	0x11, 0x34, 0x18, 0xa7, 0x71, 0x10, 0x85, 0x9e, 0xd5, 0xb3, 0xfa, 0x36, 0xde, 0x51, 0xe6, 0x20,
	0x44, 0x08, 0xb6, 0x2f, 0x59, 0x98, 0x7a, 0x35, 0xed, 0xd5, 0xdf, 0xe8, 0x10, 0x6c, 0xc9, 0x24,
	0xb9, 0x0e, 0x66, 0x94, 0x7a, 0x5b, 0x3d, 0xab, 0x5f, 0xc7, 0x4d, 0xed, 0xf8, 0x99, 0x52, 0xb4,
	0x0f, 0x3b, 0x09, 0x9d, 0x93, 0xe4, 0xad, 0xb7, 0x9d, 0x1d, 0x94, 0x59, 0xe8, 0x73, 0x00, 0xdd,
	0x3d, 0x90, 0x29, 0xa7, 0x5e, 0xbd, 0x67, 0xf5, 0x3b, 0xc7, 0xee, 0xb3, 0x6c, 0x3a, 0x3d, 0xc6,
	0x24, 0xe5, 0x14, 0xdb, 0x2c, 0xff, 0x44, 0x07, 0xd0, 0xbc, 0x62, 0x2c, 0x14, 0x6a, 0xa6, 0x1d,
	0xdd, 0xa4, 0xa1, 0xed, 0x41, 0x88, 0xba, 0xd0, 0x9c, 0xb2, 0x58, 0x92, 0xa9, 0x14, 0x5e, 0x43,
	0x77, 0x59, 0xda, 0xe8, 0x63, 0xe8, 0x98, 0xef, 0x20, 0x5e, 0xcc, 0x2f, 0x69, 0xe2, 0x35, 0x75,
	0x46, 0xdb, 0x78, 0x87, 0xda, 0xe9, 0xff, 0x6d, 0xc1, 0x6e, 0xe1, 0x0e, 0x04, 0x47, 0x1e, 0x34,
	0xb4, 0x31, 0x64, 0x66, 0xdd, 0xdc, 0x44, 0x8f, 0xc1, 0x9e, 0x44, 0x73, 0x2a, 0x24, 0x99, 0x73,
	0xbd, 0xb1, 0x8d, 0xef, 0x1c, 0x6a, 0x9c, 0x21, 0x8b, 0xa7, 0xf4, 0x42, 0x26, 0x66, 0xe9, 0xa5,
	0xad, 0x62, 0xe3, 0x84, 0x72, 0x92, 0x0e, 0x42, 0xbd, 0xb4, 0x8d, 0x97, 0xb6, 0x8a, 0x5d, 0x44,
	0x57, 0xb1, 0xda, 0x56, 0x6f, 0x68, 0xe3, 0xa5, 0xad, 0x66, 0x19, 0x93, 0x54, 0x99, 0x66, 0xc3,
	0xdc, 0xf4, 0x9f, 0xc3, 0x83, 0xdf, 0xe8, 0xf4, 0x0d, 0x91, 0x66, 0x38, 0x19, 0xcd, 0x52, 0x05,
	0xa1, 0x07, 0x0d, 0x4c, 0x6f, 0xce, 0x88, 0x24, 0x1a, 0xc2, 0x16, 0xce, 0x4d, 0xff, 0x53, 0x78,
	0x58, 0x51, 0x21, 0x38, 0xea, 0x40, 0x6d, 0x74, 0xae, 0xb3, 0x9b, 0xb8, 0x36, 0x3a, 0xf7, 0xff,
	0x80, 0x0e, 0xa6, 0xb3, 0x45, 0x1c, 0x2e, 0x79, 0xe1, 0xc2, 0xd6, 0xc2, 0x70, 0xa2, 0x8d, 0xd5,
	0xa7, 0x82, 0x25, 0xc3, 0x31, 0x5e, 0xde, 0x12, 0x33, 0xb7, 0xf4, 0x3d, 0xb4, 0x19, 0xa7, 0x09,
	0x91, 0xcc, 0xa0, 0xbc, 0xa5, 0x51, 0x3e, 0x30, 0x28, 0x9b, 0xa3, 0x4d, 0x86, 0x86, 0xbb, 0xc5,
	0x56, 0x2c, 0x7f, 0x0f, 0x76, 0x0b, 0xed, 0x05, 0xf7, 0xbf, 0xc8, 0x47, 0xcf, 0x02, 0xff, 0x65,
	0xdb, 0x3e, 0xec, 0x57, 0x95, 0x54, 0xac, 0xfb, 0xd7, 0x16, 0xd8, 0xba, 0xd5, 0x20, 0x9e, 0xb1,
	0xc2, 0x62, 0x56, 0x71, 0xb1, 0x23, 0x70, 0x32, 0xc2, 0xf3, 0x24, 0x9a, 0x52, 0xbd, 0x76, 0x1d,
	0x83, 0x76, 0x8d, 0x95, 0x47, 0xd5, 0x72, 0x92, 0x06, 0x32, 0x9a, 0x53, 0x43, 0x8f, 0x06, 0x27,
	0xa9, 0x62, 0x88, 0xd2, 0x83, 0x90, 0x44, 0x2e, 0x84, 0xa6, 0x46, 0x1d, 0x1b, 0x6b, 0x45, 0x27,
	0xf5, 0x82, 0x4e, 0x8e, 0xc0, 0xb9, 0x24, 0xd3, 0xb7, 0x81, 0x09, 0x66, 0xbc, 0x00, 0xe5, 0xc2,
	0x59, 0xc2, 0x21, 0xd8, 0x3a, 0x41, 0x37, 0x33, 0xec, 0x57, 0x0e, 0xdd, 0xed, 0x43, 0x70, 0x6e,
	0xdf, 0x05, 0x32, 0x21, 0x21, 0x55, 0x7b, 0x64, 0xd4, 0xb7, 0x6f, 0xdf, 0x4d, 0x94, 0x67, 0xc8,
	0x54, 0xf1, 0x54, 0xb3, 0x3e, 0x20, 0xd2, 0xb3, 0x8d, 0x74, 0xb4, 0xe3, 0x44, 0xa2, 0x8f, 0xa0,
	0xc5, 0x13, 0x16, 0x2e, 0xa6, 0x32, 0x83, 0x0f, 0xf4, 0xc0, 0x8e, 0xf1, 0xad, 0x89, 0xd2, 0x29,
	0x8a, 0xf2, 0x08, 0x9c, 0x6c, 0xb5, 0x20, 0x26, 0x73, 0xea, 0xb5, 0xb2, 0xc1, 0x33, 0xd7, 0x90,
	0xcc, 0x29, 0xfa, 0x11, 0xdc, 0x5b, 0x0d, 0x4c, 0xa0, 0xee, 0x8a, 0x93, 0x84, 0xcc, 0xbd, 0x76,
	0xcf, 0xea, 0x3b, 0xc7, 0xfb, 0x86, 0x21, 0x25, 0x41, 0xe2, 0x4e, 0x96, 0x3f, 0x26, 0xe9, 0x58,
	0x65, 0xfb, 0x9f, 0xc1, 0xee, 0x4b, 0x2a, 0x97, 0x90, 0x29, 0x1e, 0x6c, 0x46, 0xcd, 0xff, 0x1a,
	0xdc, 0x62, 0xb6, 0xe0, 0xe8, 0x09, 0x6c, 0x47, 0xf1, 0x2c, 0x4b, 0x75, 0x8a, 0xef, 0x8f, 0xce,
	0xd1, 0x51, 0xff, 0xc9, 0x5d, 0xa5, 0xc8, 0x1b, 0xad, 0x29, 0xc1, 0xff, 0x06, 0xf6, 0x4a, 0x59,
	0x59, 0x83, 0xeb, 0x48, 0x48, 0xcf, 0xea, 0x6d, 0x55, 0x37, 0x50, 0x51, 0xff, 0x15, 0xec, 0xbd,
	0x22, 0x62, 0x4c, 0xd2, 0x28, 0xbe, 0xba, 0x47, 0x6b, 0x65, 0x40, 0x6a, 0x6b, 0x80, 0xf8, 0x9f,
	0x00, 0x2a, 0x9f, 0x24, 0xb8, 0x3a, 0xea, 0x0d, 0x11, 0x86, 0xea, 0xea, 0xd3, 0xff, 0x0e, 0x3a,
	0xa7, 0x24, 0x9e, 0xd2, 0xeb, 0xff, 0x25, 0x6d, 0x25, 0xcd, 0x42, 0xb9, 0xe0, 0xfe, 0x73, 0x78,
	0xff, 0x24, 0x9c, 0x47, 0x71, 0xe9, 0xd8, 0x7b, 0x00, 0xd9, 0x87, 0x07, 0xeb, 0x15, 0x82, 0x3f,
	0x3d, 0x03, 0xb4, 0xfe, 0x36, 0x20, 0x17, 0x5a, 0x78, 0x34, 0x09, 0x7e, 0x8d, 0xa3, 0xdf, 0x69,
	0x22, 0xa8, 0xfb, 0x1e, 0x6a, 0x83, 0xad, 0x3c, 0x27, 0x67, 0xaf, 0x07, 0x43, 0xd7, 0xca, 0xcd,
	0xd7, 0x83, 0x53, 0x3c, 0x72, 0x6b, 0x4f, 0xbf, 0x32, 0x62, 0xd6, 0xc5, 0xbb, 0xe0, 0x14, 0x6b,
	0x1d, 0x68, 0x8c, 0x26, 0xc1, 0xc5, 0x60, 0xf2, 0xc2, 0xb5, 0x50, 0x0b, 0x9a, 0xa3, 0x49, 0xf0,
	0x72, 0x34, 0x3a, 0xbb, 0x70, 0x6b, 0xc7, 0xff, 0x6c, 0x43, 0x5d, 0x57, 0xa2, 0x6f, 0xc1, 0x59,
	0xa1, 0x20, 0x7a, 0x58, 0x45, 0xcb, 0x9b, 0xee, 0x06, 0xb6, 0xa2, 0x21, 0xec, 0xad, 0x3d, 0xb3,
	0xe8, 0xd0, 0x24, 0x57, 0x3d, 0xd9, 0xdd, 0xc7, 0x9b, 0x83, 0x82, 0xab, 0x69, 0x56, 0x9e, 0xc3,
	0xe5, 0x34, 0xc5, 0x17, 0x7a, 0x39, 0x4d, 0xe9, 0xe5, 0x44, 0xbf, 0x00, 0x5a, 0x7f, 0x06, 0x51,
	0xb1, 0x63, 0xe9, 0x51, 0xed, 0x7e, 0x70, 0x4f, 0x54, 0x70, 0xf4, 0x03, 0xb4, 0x56, 0x05, 0x85,
	0xf2, 0xd6, 0x25, 0x4d, 0x76, 0x1f, 0x55, 0xfa, 0x05, 0x47, 0x3f, 0x41, 0xbb, 0xa0, 0x18, 0x54,
	0xce, 0xcc, 0xd5, 0xd6, 0xf5, 0xaa, 0x03, 0x82, 0xa3, 0x17, 0xd0, 0x29, 0x12, 0x1e, 0xe5, 0xb9,
	0x6b, 0x8a, 0xea, 0x1e, 0x6c, 0x88, 0x64, 0x97, 0xbb, 0x42, 0xc3, 0x3b, 0xa8, 0x0b, 0x64, 0xbe,
	0x83, 0xba, 0xc8, 0x58, 0x74, 0x0e, 0x6e, 0x99, 0xc9, 0xa8, 0x6b, 0x72, 0x2b, 0x44, 0xd1, 0x3d,
	0xdc, 0x18, 0x13, 0xfc, 0x72, 0x47, 0xff, 0x9c, 0x7d, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x51, 0xe8, 0x2f, 0xab, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	WechatOrderNotify(ctx context.Context, in *WechatOrderNotifyReq, opts ...grpc.CallOption) (*WechatOrderNotifyResp, error)
	RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error)
	WechatRefundNotify(ctx context.Context, in *WechatRefundNotifyReq, opts ...grpc.CallOption) (*WechatRefundNotifyResp, error)
	GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*GetOrderInfoResp, error)
	GetOrdersInfo(ctx context.Context, in *GetOrdersInfoReq, opts ...grpc.CallOption) (*GetOrdersInfoResp, error)
	HasPayingOrder(ctx context.Context, in *HasPayingOrderReq, opts ...grpc.CallOption) (*HasPayingOrderResp, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	AdminCancelOrder(ctx context.Context, in *AdminCancelOrderReq, opts ...grpc.CallOption) (*AdminCancelOrderResp, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) WechatOrderNotify(ctx context.Context, in *WechatOrderNotifyReq, opts ...grpc.CallOption) (*WechatOrderNotifyResp, error) {
	out := new(WechatOrderNotifyResp)
	err := c.cc.Invoke(ctx, "/order.Order/WechatOrderNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error) {
	out := new(RefundOrderResp)
	err := c.cc.Invoke(ctx, "/order.Order/RefundOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) WechatRefundNotify(ctx context.Context, in *WechatRefundNotifyReq, opts ...grpc.CallOption) (*WechatRefundNotifyResp, error) {
	out := new(WechatRefundNotifyResp)
	err := c.cc.Invoke(ctx, "/order.Order/WechatRefundNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*GetOrderInfoResp, error) {
	out := new(GetOrderInfoResp)
	err := c.cc.Invoke(ctx, "/order.Order/GetOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrdersInfo(ctx context.Context, in *GetOrdersInfoReq, opts ...grpc.CallOption) (*GetOrdersInfoResp, error) {
	out := new(GetOrdersInfoResp)
	err := c.cc.Invoke(ctx, "/order.Order/GetOrdersInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) HasPayingOrder(ctx context.Context, in *HasPayingOrderReq, opts ...grpc.CallOption) (*HasPayingOrderResp, error) {
	out := new(HasPayingOrderResp)
	err := c.cc.Invoke(ctx, "/order.Order/HasPayingOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	out := new(CancelOrderResp)
	err := c.cc.Invoke(ctx, "/order.Order/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) AdminCancelOrder(ctx context.Context, in *AdminCancelOrderReq, opts ...grpc.CallOption) (*AdminCancelOrderResp, error) {
	out := new(AdminCancelOrderResp)
	err := c.cc.Invoke(ctx, "/order.Order/AdminCancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	WechatOrderNotify(context.Context, *WechatOrderNotifyReq) (*WechatOrderNotifyResp, error)
	RefundOrder(context.Context, *RefundOrderReq) (*RefundOrderResp, error)
	WechatRefundNotify(context.Context, *WechatRefundNotifyReq) (*WechatRefundNotifyResp, error)
	GetOrderInfo(context.Context, *GetOrderInfoReq) (*GetOrderInfoResp, error)
	GetOrdersInfo(context.Context, *GetOrdersInfoReq) (*GetOrdersInfoResp, error)
	HasPayingOrder(context.Context, *HasPayingOrderReq) (*HasPayingOrderResp, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error)
	AdminCancelOrder(context.Context, *AdminCancelOrderReq) (*AdminCancelOrderResp, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) CreateOrder(ctx context.Context, req *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServer) WechatOrderNotify(ctx context.Context, req *WechatOrderNotifyReq) (*WechatOrderNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatOrderNotify not implemented")
}
func (*UnimplementedOrderServer) RefundOrder(ctx context.Context, req *RefundOrderReq) (*RefundOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundOrder not implemented")
}
func (*UnimplementedOrderServer) WechatRefundNotify(ctx context.Context, req *WechatRefundNotifyReq) (*WechatRefundNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatRefundNotify not implemented")
}
func (*UnimplementedOrderServer) GetOrderInfo(ctx context.Context, req *GetOrderInfoReq) (*GetOrderInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (*UnimplementedOrderServer) GetOrdersInfo(ctx context.Context, req *GetOrdersInfoReq) (*GetOrdersInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersInfo not implemented")
}
func (*UnimplementedOrderServer) HasPayingOrder(ctx context.Context, req *HasPayingOrderReq) (*HasPayingOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPayingOrder not implemented")
}
func (*UnimplementedOrderServer) CancelOrder(ctx context.Context, req *CancelOrderReq) (*CancelOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedOrderServer) AdminCancelOrder(ctx context.Context, req *AdminCancelOrderReq) (*AdminCancelOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminCancelOrder not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_WechatOrderNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatOrderNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).WechatOrderNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/WechatOrderNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).WechatOrderNotify(ctx, req.(*WechatOrderNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_RefundOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).RefundOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/RefundOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).RefundOrder(ctx, req.(*RefundOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_WechatRefundNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatRefundNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).WechatRefundNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/WechatRefundNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).WechatRefundNotify(ctx, req.(*WechatRefundNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderInfo(ctx, req.(*GetOrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrdersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrdersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetOrdersInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrdersInfo(ctx, req.(*GetOrdersInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_HasPayingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPayingOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).HasPayingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/HasPayingOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).HasPayingOrder(ctx, req.(*HasPayingOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_AdminCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).AdminCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/AdminCancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).AdminCancelOrder(ctx, req.(*AdminCancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "WechatOrderNotify",
			Handler:    _Order_WechatOrderNotify_Handler,
		},
		{
			MethodName: "RefundOrder",
			Handler:    _Order_RefundOrder_Handler,
		},
		{
			MethodName: "WechatRefundNotify",
			Handler:    _Order_WechatRefundNotify_Handler,
		},
		{
			MethodName: "GetOrderInfo",
			Handler:    _Order_GetOrderInfo_Handler,
		},
		{
			MethodName: "GetOrdersInfo",
			Handler:    _Order_GetOrdersInfo_Handler,
		},
		{
			MethodName: "HasPayingOrder",
			Handler:    _Order_HasPayingOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Order_CancelOrder_Handler,
		},
		{
			MethodName: "AdminCancelOrder",
			Handler:    _Order_AdminCancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
